const Vegetables = [
    {
        id: "1",
        name: "Basil Leaves (100 grams)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009309_basil-leaves-100-gm-ahmed-co_125.jpeg",
        price: 140,
        quantity: 0,
        added: false,
      },
      {
        id: "2",
        name: "Broccoli (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009583_broccoli-sabz-gobi-1-kg-local_125.jpeg",
        price: 1117,
        quantity: 0,
        added: false,
      },
      {
        id: "3",
        name: "Cabbage (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0008950_chinese-cabbage-1-kg-local_125.jpeg",
        price: 56,
        quantity: 0,
        added: false,
      },
      {
        id: "5",
        name: "Red Cabbage (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/001/0011336_red-cabbage-1-kg_125.jpeg",
        price: 327,
        quantity: 0,
        added: false,
      },
      {
        id: "6",
        name: "Tomatoes (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009066_tomatoes-tamatar-1-kg_125.jpeg",
        price: 122,
        quantity: 0,
        added: false,
      },
      {
        id: "7",
        name: "Potatoes (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0008955_medium-potatoes-darmayane-aloo-1-kg_125.jpeg",
        price: 76,
        quantity: 0,
        added: false,
      },
      {
        id: "8",
        name: "Sweet Potato (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009019_sweet-potato-shakarkandi-1-kg_125.gif",
        price: 75,
        quantity: 0,
        added: false,
      },
      {
        id: "9",
        name: "Red Potato (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009004_medium-red-potatoes-laal-aloo-1-kg_125.jpeg",
        price: 94,
        quantity: 0,
        added: false,
      },
      {
        id: "10",
        name: "Cocumber (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0008958_cucumber-kheera-1-kg_125.jpeg",
        price: 35,
        quantity: 0,
        added: false,
      },
      {
        id: "11",
        name: "Round Gourd (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009024_round-gourd-tinda-1-kg_125.jpeg",
        price: 158,
        quantity: 0,
        added: false,
      },
      {
        id: "12",
        name: "Bitter Gourd (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009017_bitter-gourd-karela-1-kg_125.gif",
        price: 72,
        quantity: 0,
        added: false,
      },
      {
        id: "13",
        name: "Cauliflower (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0008984_cauliflower-phool-gobhi-1-kg_125.jpeg",
        price: 75,
        quantity: 0,
        added: false,
      },
      {
        id: "15",
        name: "Round Brinjal (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009010_round-brinjal-gol-baingan-1-kg_125.gif",
        price: 25,
        quantity: 0,
        added: false,
      },
      {
        id: "21",
        name: "Beetroot (1 Kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009020_beetroot-chukandar-1-kg_125.jpeg",
        price: 114,
        quantity: 0,
        added: false,
      },
      {
        id: "23",
        name: "Cilantro (1 pcs)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009310_cilantro-dhanyan-bundle_125.jpeg",
        price: 14,
        quantity: 0,
        added: false,
      },
      {
        id: "24",
        name: "PepperMint (1 pcs)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009316_peppermint-pudina-bundle_125.jpeg",
        price: 23,
        quantity: 0,
        added: false,
      },
      {
        id: "25",
        name: "Spring Onion (1 kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0008974_spring-onion-hara-pyaz-1-kg_125.jpeg",
        price: 96,
        quantity: 0,
        added: false,
      },
      {
        id: "26",
        name: "Spinach (1 kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0009321_spinach-palak-1-kg_125.jpeg",
        price: 26,
        quantity: 0,
        added: false,
      },
      
]
export default Vegetables;