const Fruits = [
    {
        id: 0,
        name: "Pomegranate (1 kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0006959_pomegranate-kandahari-annar-1-kg-grade-a_125.jpeg",
        price: 261,
        quantity: 0,
        added: false,
    },
    {
        id: 1,
        name: "Red Apple (1 kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/001/0011436_red-apple-kala-kullu-1-kg-grade-a_125.jpeg",
        price: 168,
        quantity: 0,
        added: false,
    },
    {
        id: 2,
        name: "Green Apple (1 kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/001/0011439_green-apple-kullu-saib-1-kg-grade-a_125.jpeg",
        price: 113,
        quantity: 0,
        added: false,
    },
    {
        id: 4,
        name: "Grape Fruit (1 pcs)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0006486_grapefruit-per-piece-local_125.jpeg",
        price: 43,
        quantity: 0,
        added: false,
    },
    {
        id: 5,
        name: "Sweet Lemon (per Dozen)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/001/0011451_sweet-lemon-mosambi-dozen-grade-a_125.jpeg",
        price: 145,
        quantity: 0,
        added: false,
    },
    {
        id: 6,
        name: "Green Grapes (per kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0002699_green-grapes-angoor-1-kg_125.jpeg",
        price: 135,
        quantity: 0,
        added: false,
    },
    {
        id: 7,
        name: "Banana (per Dozen)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/001/0010248_banana-kela-dozen-grade-b_125.jpeg",
        price: 86,
        quantity: 0,
        added: false,
    },
    {
        id: 9,
        name: "Sapodilla (1 kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/001/0011411_sapodilla-cheeku-1-kg_125.jpeg",
        price: 117,
        quantity: 0,
        added: false,
    },
    {
        id: 10,
        name: "Sweet Melon (1 kg)",
        src: "https://backend.mandiexpress.pk/content/images/thumbs/000/0008274_sweet-melon-cantaloupe-kharbuza-075-1-kg-grade-a_125.gif",
        price: 162,
        quantity: 0,
        added: false,
    },
]
export default Fruits;